const DeviceState = {
  STATE_AVAILABLE: 0,
  STATE_STARTED: 1,
  STATE_CHARGING: 2,
  STATE_STOPPED: 3,
  STATE_POWER_FAIL: 4,
  STATE_LOW_VOLTAGE: 6,
  STATE_UNKNOWN_FAULT: 10,
};

const DeviceNetworkStatus = {
  NETWORK_NONE: 0,
  NETWORK_WIFI: 1,
  NETWORK_BT: 2,
}

const DeviceStopReason = {
  STOP_REASON_REMOTE: 1,
  STOP_REASON_NO_LOAD: 2,
  STOP_REASON_TIMEOUT: 3,
  STOP_REASON_COMPLETED: 4,
  STOP_REASON_POWERLOSS: 5,
  STOP_REASON_MAX: 9,
}